package com.google.android.gms.internal.ads;

import android.content.Context;
import android.content.SharedPreferences.Editor;
import android.support.v7.widget.helper.ItemTouchHelper.Callback;
import com.android.volley.BuildConfig;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.apache.commons.lang3.time.DateUtils;
import org.json.JSONObject;

@bu
public final class akl {
    public static final akb<Long> A = akb.a(1, "gads:video:spinner:jank_threshold_ms", 50);
    public static final akb<Boolean> B = akb.a(1, "gads:video:aggressive_media_codec_release", Boolean.valueOf(false));
    public static final akb<Boolean> C = akb.a(1, "gads:memory_bundle:debug_info", Boolean.valueOf(false));
    public static final akb<Boolean> D = akb.a(1, "gads:memory_bundle:runtime_info", Boolean.valueOf(true));
    public static final akb<String> E = akb.a(1, "gads:video:codec_query_mime_types", "");
    public static final akb<Integer> F = akb.a(1, "gads:video:codec_query_minimum_version", 16);
    public static final akb<Boolean> G = akb.a(0, "gads:looper_for_gms_client:enabled", Boolean.valueOf(true));
    public static final akb<Boolean> H = akb.a(0, "gads:sw_ad_request_service:enabled", Boolean.valueOf(true));
    public static final akb<String> I = akb.a(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
    public static final akb<String> J = akb.a(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
    public static final akb<String> K = akb.a(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
    public static final akb<String> L = akb.a(1, "gad:mraid:version", "2.0");
    public static final akb<Boolean> M = akb.a(1, "gads:mraid:unload", Boolean.valueOf(false));
    public static final akb<Boolean> N = akb.a(0, "gads:enabled_sdk_csi", Boolean.valueOf(false));
    public static final akb<String> O = akb.a(0, "gads:sdk_csi_server", "https://csi.gstatic.com/csi");
    public static final akb<Boolean> P = akb.a(0, "gads:sdk_csi_write_to_file", Boolean.valueOf(false));
    public static final akb<Boolean> Q = akb.a(0, "gads:enable_content_fetching", Boolean.valueOf(true));
    public static final akb<Integer> R = akb.a(0, "gads:content_length_weight", 1);
    public static final akb<Integer> S = akb.a(0, "gads:content_age_weight", 1);
    public static final akb<Integer> T = akb.a(0, "gads:min_content_len", 11);
    public static final akb<Integer> U = akb.a(0, "gads:fingerprint_number", 10);
    public static final akb<Integer> V = akb.a(0, "gads:sleep_sec", 10);
    public static final akb<Boolean> W = akb.a(1, "gads:enable_content_url_hash", Boolean.valueOf(true));
    public static final akb<Integer> X = akb.a(1, "gads:content_vertical_fingerprint_number", 100);
    public static final akb<Boolean> Y = akb.a(1, "gads:enable_content_vertical_hash", Boolean.valueOf(true));
    public static final akb<Integer> Z = akb.a(1, "gads:content_vertical_fingerprint_bits", 23);
    public static final akb<String> a = akb.a(0, "gads:sdk_core_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html");
    public static final akb<Boolean> aA = akb.a(0, "gads:corewebview:javascript_engine", Boolean.valueOf(false));
    public static final akb<Boolean> aB = akb.a(1, "gad:webview:inject_scripts", Boolean.valueOf(false));
    public static final akb<Boolean> aC = akb.a(0, "gads:webview:permission:disabled", Boolean.valueOf(false));
    public static final akb<Boolean> aD = akb.a(1, "gads:rewarded:adapter_initialization_enabled", Boolean.valueOf(false));
    public static final akb<Long> aE = akb.a(1, "gads:rewarded:adapter_timeout_ms", 20000);
    public static final akb<Boolean> aF = akb.a(1, "gads:rewarded:ad_metadata_enabled", Boolean.valueOf(false));
    public static final akb<Boolean> aG = akb.a(1, "gads:app_activity_tracker:enabled", Boolean.valueOf(true));
    public static final akb<Long> aH = akb.a(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500);
    public static final akb<Long> aI = akb.a(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5));
    public static final akb<Boolean> aJ = akb.a(1, "gads:adid_values_in_adrequest:enabled", Boolean.valueOf(false));
    public static final akb<Long> aK = akb.a(1, "gads:adid_values_in_adrequest:timeout", 2000);
    public static final akb<Boolean> aL = akb.a(1, "gads:disable_adid_values_in_ms", Boolean.valueOf(false));
    public static final akb<Boolean> aM = akb.a(1, "gads:enable_ad_loader_manager", Boolean.valueOf(true));
    public static final akb<Boolean> aN = akb.a(1, "gads:ad_manager_enforce_arp_invariant:enabled", Boolean.valueOf(true));
    public static final akb<Boolean> aO = akb.a(1, "gads:ad_manager:admob_extra:new_bundle", Boolean.valueOf(true));
    public static final akb<Long> aP = akb.a(1, "gads:ad_overlay:delay_page_close_timeout_ms", 5000);
    public static final akb<Boolean> aQ = akb.a(1, "gads:interstitial_ad_immersive_mode", Boolean.valueOf(true));
    public static final akb<Boolean> aR = akb.a(1, "gads:custom_close_blocking:enabled", Boolean.valueOf(false));
    public static final akb<Boolean> aS = akb.a(1, "gads:disabling_closable_area:enabled", Boolean.valueOf(false));
    public static final akb<Boolean> aT = akb.a(1, "gads:interstitial_ad_pool:enabled", Boolean.valueOf(false));
    public static final akb<Boolean> aU = akb.a(1, "gads:interstitial_ad_pool:enabled_for_rewarded", Boolean.valueOf(false));
    public static final akb<String> aV = akb.a(1, "gads:interstitial_ad_pool:schema", "customTargeting");
    public static final akb<String> aW = akb.a(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
    public static final akb<Integer> aX = akb.a(1, "gads:interstitial_ad_pool:max_pools", 3);
    public static final akb<Integer> aY = akb.a(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
    public static final akb<Integer> aZ = akb.a(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
    public static final akb<Integer> aa = akb.a(1, "gads:content_vertical_fingerprint_ngram", 3);
    public static final akb<String> ab = akb.a(1, "gads:content_fetch_view_tag_id", "googlebot");
    public static final akb<String> ac = akb.a(1, "gads:content_fetch_exclude_view_tag", "none");
    public static final akb<Boolean> ad = akb.a(0, "gad:app_index_enabled", Boolean.valueOf(true));
    public static final akb<Boolean> ae = akb.a(1, "gads:content_fetch_disable_get_title_from_webview", Boolean.valueOf(false));
    public static final akb<Boolean> af = akb.a(0, "gads:app_index:without_content_info_present:enabled", Boolean.valueOf(true));
    public static final akb<Long> ag = akb.a(0, "gads:app_index:timeout_ms", 1000);
    public static final akb<Boolean> ah = akb.a(0, "gads:kitkat_interstitial_workaround:enabled", Boolean.valueOf(true));
    public static final akb<Boolean> ai = akb.a(0, "gads:interstitial_follow_url", Boolean.valueOf(true));
    public static final akb<Boolean> aj = akb.a(0, "gads:interstitial_follow_url:register_click", Boolean.valueOf(true));
    public static final akb<Boolean> ak = akb.a(0, "gads:ad_key_enabled", Boolean.valueOf(false));
    public static final akb<Boolean> al = akb.a(1, "gads:sai:enabled", Boolean.valueOf(true));
    public static final akb<Boolean> am = akb.a(1, "gads:sai:banner_ad_enabled", Boolean.valueOf(true));
    public static final akb<Boolean> an = akb.a(1, "gads:sai:native_ad_enabled", Boolean.valueOf(true));
    public static final akb<Boolean> ao = akb.a(1, "gads:sai:interstitial_ad_enabled", Boolean.valueOf(true));
    public static final akb<Boolean> ap = akb.a(1, "gads:sai:rewardedvideo_ad_enabled", Boolean.valueOf(true));
    public static final akb<String> aq = akb.a(1, "gads:sai:click_ping_schema_v2", "^[^?]*(/aclk\\?|/pcs/click\\?).*");
    public static final akb<String> ar = akb.a(1, "gads:sai:impression_ping_schema_v2", "^[^?]*/adview.*");
    public static final akb<Boolean> as = akb.a(1, "gads:sai:click_gmsg_enabled", Boolean.valueOf(true));
    public static final akb<Boolean> at = akb.a(1, "gads:sai:using_macro:enabled", Boolean.valueOf(false));
    public static final akb<String> au = akb.a(1, "gads:sai:ad_event_id_macro_name", "[gw_fbsaeid]");
    public static final akb<Long> av = akb.a(1, "gads:sai:timeout_ms", -1);
    public static final akb<Integer> aw = akb.a(1, "gads:sai:scion_thread_pool_size", 5);
    public static final akb<Boolean> ax = akb.a(1, "gads:x_seconds_rewarded:enable", Boolean.valueOf(false));
    public static final akb<Boolean> ay = akb.a(1, "gads:webview:ignore_over_scroll", Boolean.valueOf(true));
    public static final akb<Boolean> az = akb.a(0, "gads:corewebview:adwebview_factory:enable", Boolean.valueOf(false));
    public static final akb<Boolean> b = akb.a(0, "gads:sdk_crash_report_enabled", Boolean.valueOf(false));
    public static final akb<Long> bA = akb.a(0, "gads:ad_loader:timeout_ms", (long) DateUtils.MILLIS_PER_MINUTE);
    public static final akb<Long> bB = akb.a(0, "gads:rendering:timeout_ms", (long) DateUtils.MILLIS_PER_MINUTE);
    public static final akb<Boolean> bC = akb.a(0, "gads:adshield:enable_adshield_instrumentation", Boolean.valueOf(false));
    public static final akb<Long> bD = akb.a(1, "gads:gestures:task_timeout", 2000);
    public static final akb<Boolean> bE = akb.a(1, "gads:gestures:asig:enabled", Boolean.valueOf(false));
    public static final akb<Boolean> bF = akb.a(1, "gads:gestures:ans:enabled", Boolean.valueOf(false));
    public static final akb<Boolean> bG = akb.a(1, "gads:gestures:tos:enabled", Boolean.valueOf(false));
    public static final akb<Boolean> bH = akb.a(1, "gads:signal:app_permissions:disabled", Boolean.valueOf(false));
    public static final akb<Boolean> bI = akb.a(1, "gads:gestures:inthex:enabled", Boolean.valueOf(false));
    public static final akb<Boolean> bJ = akb.a(1, "gads:gestures:hpk:enabled", Boolean.valueOf(true));
    public static final akb<String> bK = akb.a(1, "gads:gestures:pk", "");
    public static final akb<Boolean> bL = akb.a(1, "gads:gestures:bs:enabled", Boolean.valueOf(true));
    public static final akb<Boolean> bM = akb.a(1, "gads:gestures:check_initialization_thread:enabled", Boolean.valueOf(false));
    public static final akb<Boolean> bN = akb.a(1, "gads:gestures:get_query_in_non_ui_thread:enabled", Boolean.valueOf(true));
    public static final akb<Boolean> bO = akb.a(0, "gass:enabled", Boolean.valueOf(true));
    public static final akb<Boolean> bP = akb.a(0, "gass:enable_int_signal", Boolean.valueOf(true));
    public static final akb<Boolean> bQ = akb.a(0, "gass:enable_ad_attestation_signal", Boolean.valueOf(true));
    public static final akb<Boolean> bR = akb.a(0, "gads:support_screen_shot", Boolean.valueOf(true));
    public static final akb<Boolean> bS = akb.a(0, "gads:use_get_drawing_cache_for_screenshot:enabled", Boolean.valueOf(true));
    public static final akb<String> bT = akb.a(1, "gads:sdk_core_constants:caps", "");
    public static final akb<Long> bU = akb.a(0, "gads:js_flags:update_interval", TimeUnit.HOURS.toMillis(12));
    public static final akb<Boolean> bV = akb.a(0, "gads:js_flags:mf", Boolean.valueOf(false));
    public static final akb<Boolean> bW = akb.a(0, "gads:custom_render:ping_on_ad_rendered", Boolean.valueOf(false));
    public static final akb<String> bX = akb.a(1, "gads:native:engine_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    public static final akb<String> bY = akb.a(1, "gads:native:video_url_with_protocol", "https://imasdk.googleapis.com/admob/sdkloader/native_video.html");
    public static final akb<Boolean> bZ = akb.a(1, "gads:enable_untrack_view_native", Boolean.valueOf(true));
    public static final akb<String> ba = akb.a(1, "gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
    public static final akb<Integer> bb = akb.a(1, "gads:interstitial_ad_pool:top_off_latency_min_millis", 0);
    public static final akb<Integer> bc = akb.a(1, "gads:interstitial_ad_pool:top_off_latency_range_millis", 0);
    public static final akb<Long> bd = akb.a(1, "gads:interstitial_ad_pool:discard_thresholds", 0);
    public static final akb<Long> be = akb.a(1, "gads:interstitial_ad_pool:miss_thresholds", 0);
    public static final akb<Float> bf = akb.a(1, "gads:interstitial_ad_pool:discard_asymptote", 0.0f);
    public static final akb<Float> bg = akb.a(1, "gads:interstitial_ad_pool:miss_asymptote", 0.0f);
    public static final akb<Boolean> bh = akb.a(0, "gads:debug_logging_feature:enable", Boolean.valueOf(false));
    public static final akb<Boolean> bi = akb.a(0, "gads:debug_logging_feature:intercept_web_view", Boolean.valueOf(false));
    public static final akb<String> bj = akb.a(1, "gads:spherical_video:vertex_shader", "");
    public static final akb<String> bk = akb.a(1, "gads:spherical_video:fragment_shader", "");
    public static final akb<Boolean> bl = akb.a(0, "gads:log:verbose_enabled", Boolean.valueOf(false));
    public static final akb<Boolean> bm = akb.a(1, "gads:include_local_global_rectangles", Boolean.valueOf(false));
    public static final akb<Long> bn = akb.a(1, "gads:position_watcher:throttle_ms", 200);
    public static final akb<Boolean> bo = akb.a(1, "gads:include_lock_screen_apps_for_visibility", Boolean.valueOf(true));
    public static final akb<Boolean> bp = akb.a(0, "gads:device_info_caching:enabled", Boolean.valueOf(true));
    public static final akb<Long> bq = akb.a(0, "gads:device_info_caching_expiry_ms:expiry", 300000);
    public static final akb<Boolean> br = akb.a(1, "gads:gen204_signals:enabled", Boolean.valueOf(false));
    public static final akb<Boolean> bs = akb.a(0, "gads:webview:error_reporting_enabled", Boolean.valueOf(false));
    public static final akb<Boolean> bt = akb.a(1, "gads:gmsg:disable_back_button:enabled", Boolean.valueOf(true));
    public static final akb<Boolean> bu = akb.a(0, "gads:gmsg:video_meta:enabled", Boolean.valueOf(true));
    public static final akb<Long> bv = akb.a(1, "gads:network:network_prediction_timeout_ms", 2000);
    public static final akb<Boolean> bw = akb.a(0, "gads:mediation:dynamite_first:admobadapter", Boolean.valueOf(true));
    public static final akb<Boolean> bx = akb.a(0, "gads:mediation:dynamite_first:adurladapter", Boolean.valueOf(true));
    public static final akb<Boolean> by = akb.a(1, "gads:bypass_adrequest_service_for_inlined_mediation", Boolean.valueOf(true));
    public static final akb<Long> bz = akb.a(0, "gads:resolve_future:default_timeout_ms", 30000);
    public static final akb<Boolean> c = akb.a(0, "gads:report_dynamite_crash_in_background_thread", Boolean.valueOf(false));
    public static final akb<Long> cA = akb.a(1, "gads:parental_controls:timeout", 2000);
    public static final akb<Boolean> cB = akb.a(0, "gads:safe_browsing:debug", Boolean.valueOf(false));
    public static final akb<Boolean> cC = akb.a(0, "gads:webview_cookie:enabled", Boolean.valueOf(true));
    public static final akb<Boolean> cD = akb.a(1, "gads:cache:bind_on_foreground", Boolean.valueOf(false));
    public static final akb<Boolean> cE = akb.a(1, "gads:cache:bind_on_init", Boolean.valueOf(false));
    public static final akb<Boolean> cF = akb.a(1, "gads:cache:bind_on_request", Boolean.valueOf(false));
    public static final akb<Long> cG = akb.a(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30));
    public static final akb<Boolean> cH = akb.a(1, "gads:cache:use_cache_data_source", Boolean.valueOf(false));
    public static final akb<Boolean> cI = akb.a(1, "gads:http_assets_cache:enabled", Boolean.valueOf(false));
    public static final akb<String> cJ = akb.a(1, "gads:http_assets_cache:regex", "(?i)https:\\/\\/(tpc\\.googlesyndication\\.com\\/(.*)|lh\\d+\\.googleusercontent\\.com\\/(.*))");
    public static final akb<Integer> cK = akb.a(1, "gads:http_assets_cache:time_out", 100);
    public static final akb<Boolean> cL = akb.a(1, "gads:chrome_custom_tabs:enabled", Boolean.valueOf(true));
    public static final akb<Boolean> cM = akb.a(1, "gads:chrome_custom_tabs_browser:enabled", Boolean.valueOf(false));
    public static final akb<Boolean> cN = akb.a(1, "gads:chrome_custom_tabs:disabled", Boolean.valueOf(false));
    public static final akb<Boolean> cO = akb.a(1, "gads:drx_in_app_preview:enabled", Boolean.valueOf(true));
    public static final akb<Boolean> cP = akb.a(1, "gads:drx_debug_signals:enabled", Boolean.valueOf(true));
    public static final akb<Boolean> cQ = akb.a(1, "gads:debug_hold_gesture:enabled", Boolean.valueOf(false));
    public static final akb<Long> cR = akb.a(1, "gads:debug_hold_gesture:time_millis", 2000);
    public static final akb<String> cS = akb.a(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
    public static final akb<String> cT = akb.a(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
    public static final akb<String> cU = akb.a(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
    public static final akb<String> cV = akb.a(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
    public static final akb<Integer> cW = akb.a(1, "gads:drx_debug:timeout_ms", 5000);
    public static final akb<Integer> cX = akb.a(1, "gad:pixel_dp_comparision_multiplier", 1);
    public static final akb<Boolean> cY = akb.a(1, "gad:interstitial_for_multi_window", Boolean.valueOf(false));
    public static final akb<Boolean> cZ = akb.a(1, "gad:interstitial_ad_stay_active_in_multi_window", Boolean.valueOf(false));
    public static final akb<Boolean> ca = akb.a(1, "gads:ignore_untrack_view_google_native", Boolean.valueOf(true));
    public static final akb<Boolean> cb = akb.a(1, "gads:reset_listeners_preparead_native", Boolean.valueOf(true));
    public static final akb<Integer> cc = akb.a(1, "gads:native_video_load_timeout", 10);
    public static final akb<Integer> cd = akb.a(1, "gads:omid:native_webview_load_timeout", 2000);
    public static final akb<String> ce = akb.a(1, "gads:ad_choices_content_description", "Ad Choices Icon");
    public static final akb<Boolean> cf = akb.a(1, "gads:clamp_native_video_player_dimensions", Boolean.valueOf(true));
    public static final akb<Boolean> cg = akb.a(1, "gads:enable_store_active_view_state", Boolean.valueOf(false));
    public static final akb<Boolean> ch = akb.a(1, "gads:enable_singleton_broadcast_receiver", Boolean.valueOf(false));
    public static final akb<Boolean> ci = akb.a(1, "gads:native:overlay_new_fix:enabled", Boolean.valueOf(true));
    public static final akb<Boolean> cj = akb.a(1, "gads:native:count_impression_for_assets", Boolean.valueOf(false));
    public static final akb<Boolean> ck = akb.a(1, "gads:native:custom_one_point_five_click:enable", Boolean.valueOf(true));
    public static final akb<Boolean> cl = akb.a(1, "gads:unified_native_ad:enable", Boolean.valueOf(true));
    public static final akb<Boolean> cm = akb.a(1, "gads:fluid_ad:use_wrap_content_height", Boolean.valueOf(false));
    public static final akb<Boolean> cn = akb.a(0, "gads:method_tracing:enabled", Boolean.valueOf(false));
    public static final akb<Long> co = akb.a(0, "gads:method_tracing:duration_ms", 30000);
    public static final akb<Integer> cp = akb.a(0, "gads:method_tracing:count", 5);
    public static final akb<Integer> cq = akb.a(0, "gads:method_tracing:filesize", 134217728);
    public static final akb<Long> cr = akb.a(1, "gads:auto_location_timeout", 2000);
    public static final akb<Boolean> cs = akb.a(1, "gads:fetch_app_settings_using_cld:enabled", Boolean.valueOf(false));
    public static final akb<Long> ct = akb.a(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000);
    public static final akb<String> cu = akb.a(0, "gads:afs:csa_webview_gmsg_ad_failed", "gmsg://noAdLoaded");
    public static final akb<String> cv = akb.a(0, "gads:afs:csa_webview_gmsg_script_load_failed", "gmsg://scriptLoadFailed");
    public static final akb<String> cw = akb.a(0, "gads:afs:csa_webview_gmsg_ad_loaded", "gmsg://adResized");
    public static final akb<String> cx = akb.a(0, "gads:afs:csa_webview_static_file_path", "/afs/ads/i/webview.html");
    public static final akb<String> cy = akb.a(0, "gads:afs:csa_webview_custom_domain_param_key", "csa_customDomain");
    public static final akb<Long> cz = akb.a(0, "gads:afs:csa_webview_adshield_timeout_ms", 1000);
    public static final akb<Boolean> d = akb.a(0, "gads:sdk_crash_report_full_stacktrace", Boolean.valueOf(false));
    private static final akb<String> dA = akb.a(0, "gads:video_stream_cache:experiment_id");
    private static final akb<Boolean> dB = akb.a(0, "gads:ad_id_app_context:enabled", Boolean.valueOf(false));
    private static final akb<Float> dC = akb.a(0, "gads:ad_id_app_context:ping_ratio", 0.0f);
    private static final akb<String> dD = akb.a(0, "gads:ad_id_app_context:experiment_id");
    private static final akb<String> dE = akb.a(0, "gads:ad_id_use_shared_preference:experiment_id");
    private static final akb<Boolean> dF = akb.a(0, "gads:ad_id_use_shared_preference:enabled", Boolean.valueOf(false));
    private static final akb<Float> dG = akb.a(0, "gads:ad_id_use_shared_preference:ping_ratio", 0.0f);
    private static final akb<Boolean> dH = akb.a(0, "gads:ad_id_use_persistent_service:enabled", Boolean.valueOf(false));
    private static final akb<Boolean> dI = akb.a(0, "gads:ad_id:use_ipc:enabled", Boolean.valueOf(false));
    private static final akb<String> dJ = akb.b(0, "gads:looper_for_gms_client:experiment_id");
    private static final akb<Boolean> dK = akb.a(0, "gads:sw_dynamite:enabled", Boolean.valueOf(true));
    private static final akb<String> dL = akb.a(0, "gads:app_index:experiment_id");
    private static final akb<String> dM = akb.a(0, "gads:kitkat_interstitial_workaround:experiment_id");
    private static final akb<String> dN = akb.a(0, "gads:interstitial_follow_url:experiment_id");
    private static final akb<Boolean> dO = akb.a(0, "gads:analytics_enabled", Boolean.valueOf(true));
    private static final akb<Integer> dP = akb.a(0, "gads:webview_cache_version", 0);
    private static final akb<String> dQ = akb.b(0, "gads:pan:experiment_id");
    private static final akb<Boolean> dR = akb.a(0, "gads:ad_serving:enabled", Boolean.valueOf(true));
    private static final akb<Boolean> dS = akb.a(1, "gads:impression_optimization_enabled", Boolean.valueOf(false));
    private static final akb<String> dT = akb.a(1, "gads:banner_ad_pool:schema", "customTargeting");
    private static final akb<Integer> dU = akb.a(1, "gads:banner_ad_pool:max_queues", 3);
    private static final akb<Integer> dV = akb.a(1, "gads:banner_ad_pool:max_pools", 3);
    private static final akb<Integer> dW = akb.a(1, "gads:heap_wastage:bytes", 0);
    private static final akb<Boolean> dX = akb.a(0, "gads:adid_reporting:enabled", Boolean.valueOf(false));
    private static final akb<Boolean> dY = akb.a(0, "gads:ad_settings_page_reporting:enabled", Boolean.valueOf(false));
    private static final akb<Boolean> dZ = akb.a(0, "gads:adid_info_gmscore_upgrade_reporting:enabled", Boolean.valueOf(false));
    public static final akb<Integer> da = akb.a(1, "gad:interstitial:close_button_padding_dip", 0);
    public static final akb<Boolean> db = akb.a(1, "gads:clearcut_logging:enabled", Boolean.valueOf(false));
    public static final akb<Boolean> dc = akb.a(1, "gads:clearcut_logging:write_to_file", Boolean.valueOf(false));
    public static final akb<Boolean> dd = akb.a(0, "gad:force_local_ad_request_service:enabled", Boolean.valueOf(false));

    /* renamed from: de reason: collision with root package name */
    public static final akb<Boolean> f2de = akb.a(0, "gad:force_dynamite_loading_enabled", Boolean.valueOf(false));
    public static final akb<Integer> df = akb.a(1, "gad:http_redirect_max_count:times", 8);
    public static final akb<Boolean> dg = akb.a(1, "gads:omid:enabled", Boolean.valueOf(false));
    public static final akb<Boolean> dh = akb.a(1, "gads:nonagon:banner:check_dp_size", Boolean.valueOf(false));
    public static final akb<Long> di = akb.a(1, "gads:mobius_linking:sdk_side_cooldown_time_threshold:ms", (long) DateUtils.MILLIS_PER_HOUR);
    public static final akb<String> dj = akb.a(0, "gads:public_beta:traffic_multiplier", BuildConfig.VERSION_NAME);
    public static final akb<Boolean> dk = akb.a(1, "gads:real_test_request:enabled", Boolean.valueOf(true));
    public static final akb<Boolean> dl = akb.a(1, "gads:real_test_request:render_webview_label", Boolean.valueOf(true));
    public static final akb<Boolean> dm = akb.a(1, "gads:real_test_request:render_native_label", Boolean.valueOf(true));
    public static final akb<Integer> dn = akb.a(1, "gads:adoverlay:b68684796:targeting_sdk:lower_bound", 27);

    /* renamed from: do reason: not valid java name */
    public static final akb<Integer> f0do = akb.a(1, "gads:adoverlay:b68684796:targeting_sdk:upper_bound", 27);
    public static final akb<Integer> dp = akb.a(1, "gads:adoverlay:b68684796:sdk_int:lower_bound", 26);
    public static final akb<Integer> dq = akb.a(1, "gads:adoverlay:b68684796:sdk_int:upper_bound", 27);
    private static final akb<String> dr = akb.a(0, "gads:sdk_core_experiment_id");
    private static final akb<String> ds = akb.a(0, "gads:sdk_core_js_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.js");
    private static final akb<Boolean> dt = akb.a(0, "gads:request_builder:singleton_webview", Boolean.valueOf(false));
    private static final akb<String> du = akb.a(0, "gads:request_builder:singleton_webview_experiment_id");
    private static final akb<Boolean> dv = akb.a(0, "gads:sdk_use_dynamic_module", Boolean.valueOf(true));
    private static final akb<String> dw = akb.a(0, "gads:sdk_use_dynamic_module_experiment_id");
    private static final akb<String> dx = akb.a(0, "gads:block_autoclicks_experiment_id");
    private static final akb<String> dy = akb.a(0, "gads:spam_app_context:experiment_id");
    private static final akb<Integer> dz = akb.a(1, "gads:http_url_connection_factory:timeout_millis", 10000);
    public static final akb<String> e = akb.a(0, "gads:sdk_crash_report_class_prefix", "com.google.");
    private static final akb<Long> eA = akb.a(1, "gads:cache:javascript_timeout_millis", 5000);
    private static final akb<Boolean> eB = akb.a(1, "gads:cache:connection_per_read", Boolean.valueOf(false));
    private static final akb<Long> eC = akb.a(1, "gads:cache:connection_timeout", 5000);
    private static final akb<Long> eD = akb.a(1, "gads:cache:read_only_connection_timeout", 5000);
    private static final akb<Boolean> eE = akb.a(0, "gads:nonagon:red_button", Boolean.valueOf(false));
    private static final akb<Boolean> eF = akb.a(1, "gads:nonagon:banner:enabled", Boolean.valueOf(false));
    private static final akb<String> eG = akb.a(1, "gads:nonagon:banner:ad_unit_exclusions", "(?!)");
    private static final akb<Boolean> eH = akb.a(1, "gads:nonagon:interstitial:enabled", Boolean.valueOf(false));
    private static final akb<String> eI = akb.a(1, "gads:nonagon:interstitial:ad_unit_exclusions", "(?!)");
    private static final akb<Boolean> eJ = akb.a(1, "gads:nonagon:rewardedvideo:enabled", Boolean.valueOf(false));
    private static final akb<Boolean> eK = akb.a(1, "gads:nonagon:mobile_ads_setting_manager:enabled", Boolean.valueOf(false));
    private static final akb<String> eL = akb.a(1, "gads:nonagon:rewardedvideo:ad_unit_exclusions", "(?!)");
    private static final akb<Boolean> eM = akb.a(1, "gads:nonagon:nativead:enabled", Boolean.valueOf(false));
    private static final akb<String> eN = akb.a(1, "gads:nonagon:nativead:app_name", "(?!)");
    private static final akb<Boolean> eO = akb.a(1, "gads:nonagon:service:enabled", Boolean.valueOf(false));
    private static final akb<Boolean> eP = akb.a(1, "gads:signals:ad_id_info:enabled", Boolean.valueOf(false));
    private static final akb<Boolean> eQ = akb.a(1, "gads:signals:app_index:enabled", Boolean.valueOf(false));
    private static final akb<Boolean> eR = akb.a(1, "gads:signals:cache:enabled", Boolean.valueOf(false));
    private static final akb<Boolean> eS = akb.a(1, "gads:signals:doritos:enabled", Boolean.valueOf(false));
    private static final akb<Boolean> eT = akb.a(1, "gads:signals:location:enabled", Boolean.valueOf(false));
    private static final akb<Boolean> eU = akb.a(1, "gads:signals:network_prediction:enabled", Boolean.valueOf(false));
    private static final akb<Boolean> eV = akb.a(1, "gads:signals:parental_control:enabled", Boolean.valueOf(false));
    private static byte[] eW;
    private static final akb<Boolean> ea = akb.a(0, "gads:request_pkg:enabled", Boolean.valueOf(true));
    private static final akb<String> eb = akb.a(0, "gads:gmsg:video_meta:experiment_id");
    private static final akb<Long> ec = akb.a(1, "gads:network:cache_prediction_duration_s", 300);
    private static final akb<Long> ed = akb.a(1, "gads:rtb_signal_timeout_ms", 1000);
    private static final akb<Boolean> ee = akb.a(0, "gads:adid_notification:first_party_check:enabled", Boolean.valueOf(true));
    private static final akb<Boolean> ef = akb.a(0, "gads:edu_device_helper:enabled", Boolean.valueOf(true));
    private static final akb<String> eg = akb.a(0, "gads:use_get_drawing_cache_for_screenshot:experiment_id");
    private static final akb<String> eh = akb.a(1, "gads:sdk_core_constants:experiment_id");
    private static final akb<Boolean> ei = akb.a(1, "gads:js_flags:disable_phenotype", Boolean.valueOf(false));
    private static final akb<String> ej = akb.a(0, "gads:native:engine_js_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/native_ads.js");
    private static final akb<String> ek = akb.a(1, "gads:native:video_url", "//imasdk.googleapis.com/admob/sdkloader/native_video.html");
    private static final akb<String> el = akb.a(1, "gads:singleton_webview_native:experiment_id");
    private static final akb<Boolean> em = akb.a(1, "gads:auto_location_for_coarse_permission", Boolean.valueOf(false));
    private static final akb<String> en = akb.b(1, "gads:auto_location_for_coarse_permission:experiment_id");
    private static final akb<String> eo = akb.b(1, "gads:auto_location_timeout:experiment_id");
    private static final akb<Long> ep = akb.a(1, "gads:auto_location_interval", -1);
    private static final akb<String> eq = akb.b(1, "gads:auto_location_interval:experiment_id");
    private static final akb<String> er = akb.a(1, "gads:fetch_app_settings_using_cld:enabled:experiment_id");
    private static final akb<String> es = akb.a(0, "gads:afs:csa:experiment_id");
    private static final akb<Boolean> et = akb.a(0, "gads:afs:csa_ad_manager_enabled", Boolean.valueOf(true));
    private static final akb<Boolean> eu = akb.a(1, "gads:parental_controls:send_from_client", Boolean.valueOf(true));
    private static final akb<Boolean> ev = akb.a(1, "gads:parental_controls:cache_results", Boolean.valueOf(true));
    private static final akb<String> ew = akb.a(0, "gads:safe_browsing:api_key", "AIzaSyDRKQ9d6kfsoZT2lUnZcZnBYvH69HExNPE");
    private static final akb<Long> ex = akb.a(0, "gads:safe_browsing:safety_net:delay_ms", 2000);
    private static final akb<Integer> ey = akb.a(1, "gads:cache:ad_request_timeout_millis", (int) Callback.DEFAULT_SWIPE_ANIMATION_DURATION);
    private static final akb<Integer> ez = akb.a(1, "gads:cache:max_concurrent_downloads", 10);
    public static final akb<Float> f = akb.a(1, "gads:trapped_exception_sample_rate", 0.01f);
    public static final akb<Boolean> g = akb.a(0, "gads:block_autoclicks", Boolean.valueOf(false));
    public static final akb<String> h = akb.a(1, "gads:video_exo_player:version", "1");
    public static final akb<Integer> i = akb.a(1, "gads:video_exo_player:connect_timeout", 8000);
    public static final akb<Integer> j = akb.a(1, "gads:video_exo_player:read_timeout", 8000);
    public static final akb<Integer> k = akb.a(1, "gads:video_exo_player:loading_check_interval", 1048576);
    public static final akb<Integer> l = akb.a(1, "gads:video_exo_player:exo_player_precache_limit", Integer.MAX_VALUE);
    public static final akb<Integer> m = akb.a(1, "gads:video_exo_player:byte_buffer_precache_limit", Integer.MAX_VALUE);
    public static final akb<Integer> n = akb.a(1, "gads:video_stream_cache:limit_count", 5);
    public static final akb<Integer> o = akb.a(1, "gads:video_stream_cache:limit_space", 8388608);
    public static final akb<Integer> p = akb.a(1, "gads:video_stream_exo_cache:buffer_size", 8388608);
    public static final akb<Long> q = akb.a(1, "gads:video_stream_cache:limit_time_sec", 300);
    public static final akb<Long> r = akb.a(1, "gads:video_stream_cache:notify_interval_millis", 125);
    public static final akb<Integer> s = akb.a(1, "gads:video_stream_cache:connect_timeout_millis", 10000);
    public static final akb<Boolean> t = akb.a(0, "gads:video:metric_reporting_enabled", Boolean.valueOf(false));
    public static final akb<String> u = akb.a(1, "gads:video:metric_frame_hash_times", "");
    public static final akb<Long> v = akb.a(1, "gads:video:metric_frame_hash_time_leniency", 500);
    public static final akb<Boolean> w = akb.a(1, "gads:video:force_watermark", Boolean.valueOf(false));
    public static final akb<Long> x = akb.a(1, "gads:video:surface_update_min_spacing_ms", 1000);
    public static final akb<Boolean> y = akb.a(1, "gads:video:spinner:enabled", Boolean.valueOf(false));
    public static final akb<Integer> z = akb.a(1, "gads:video:spinner:scale", 4);

    public static List<String> a() {
        return ajh.e().a();
    }

    public static void a(Context context) {
        jg.a(context, new akm(context));
        int intValue = ((Integer) ajh.f().a(dW)).intValue();
        if (intValue > 0 && eW == null) {
            eW = new byte[intValue];
        }
    }

    public static void a(Context context, int i2, JSONObject jSONObject) {
        ajh.d();
        Editor edit = context.getSharedPreferences("google_ads_flags", 0).edit();
        ajh.e().a(edit, 1, jSONObject);
        ajh.d();
        edit.commit();
    }

    public static List<String> b() {
        return ajh.e().b();
    }
}
